name: Build IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Default Scheme
      run: |
        scheme_list=$(xcodebuild -list -json | tr -d "\n")
        default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
        echo "DEFAULT_SCHEME=$default" >> $GITHUB_ENV

    - name: Build Archive
      run: |
        xcodebuild archive \
          -project ThreeOneOSFive.xcodeproj \
          -scheme "ThreeOneOSFive" \
          -configuration Release \
          -archivePath $PWD/build/ThreeOneOSFive.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ENABLE_BITCODE=NO | xcpretty

    - name: Export IPA
      run: |
        mkdir -p build/Payload
        cp -r build/ThreeOneOSFive.xcarchive/Products/Applications/ThreeOneOSFive.app build/Payload/
        cd build
        zip -r YABAOCHEAT-Patcher.ipa Payload

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: YABAOCHEAT-Patcher
        path: build/YABAOCHEAT-Patcher.ipa
